### PR TITLE
Stopwatch-UI

### PR DESCRIPTION
**Pull request by kaiceniza**
- Display including the milliseconds
- Deleted unnecessary files

### CODE REVIEW

**Comment by SpookyGlitches** [comment]
It doesn't seem to update the records sa akoang end. Also, the player can't proceed sa lvl 3. Remove spaces lang sa label nga stopwatch.

**Comment by kaiceniza** [comment]
sorry check balik new commit

**Review by SpookyGlitches — CHANGES_REQUESTED** [review]
- Convert GameIcon.png to .ico file, follow lang sa Godot docu.
- Remove TheLostAliend.exe and TheLostAliend.pck

**Comment by kaiceniza** [comment]
okioki noted

**Review by kaiceniza — COMMENTED** [review]
changes added

**Review by SpookyGlitches — APPROVED** [review]
pog

**Pull request merged**
